"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { TrendingUp, TrendingDown, Brain, Loader2 } from "lucide-react";

interface AIInsightsProps {
    symbol: string;
    stockName: string;
}

interface AIInsightData {
    bullCase: string;
    bearCase: string;
}

export default function AIInsights({ symbol, stockName }: AIInsightsProps) {
    const [isEnabled, setIsEnabled] = useState(false);
    const [loading, setLoading] = useState(false);
    const [data, setData] = useState<AIInsightData | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleToggle = async () => {
        if (!isEnabled && !data && !loading) {
            setLoading(true);
            setError(null);
            try {
                const res = await fetch(`/api/ai-thesis?symbol=${encodeURIComponent(symbol)}&name=${encodeURIComponent(stockName)}`);
                const json = await res.json();
                if (res.ok && !json.error) {
                    setData(json);
                } else {
                    setError(json.error || "Failed to fetch AI insights");
                }
            } catch {
                setError("An error occurred while fetching AI insights.");
            } finally {
                setLoading(false);
            }
        }
        setIsEnabled(!isEnabled);
    };

    return (
        <div className="bg-gray-900/50 backdrop-blur-xl border border-gray-800 rounded-3xl p-6 shadow-xl mb-4">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-indigo-500/10 rounded-xl">
                        <Brain className="w-6 h-6 text-indigo-400" />
                    </div>
                    <div>
                        <h3 className="text-xl font-semibold text-white">AI Analyst Thesis</h3>
                        <p className="text-gray-400 text-sm">Bull & Bear Case generated by Claude</p>
                    </div>
                </div>

                {/* Toggle Switch */}
                <button
                    onClick={handleToggle}
                    className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-900 ${isEnabled ? 'bg-indigo-500' : 'bg-gray-700'}`}
                >
                    <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${isEnabled ? 'translate-x-6' : 'translate-x-1'}`} />
                </button>
            </div>

            <AnimatePresence>
                {isEnabled && (
                    <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="overflow-hidden"
                    >
                        <div className="mt-6 border-t border-gray-800 pt-6"></div>
                        {loading && (
                            <div className="flex flex-col items-center justify-center py-8 text-gray-400 space-y-3">
                                <Loader2 className="w-8 h-8 animate-spin text-indigo-500" />
                                <span className="text-sm animate-pulse">Analyzing market sentiment and forming a thesis...</span>
                            </div>
                        )}

                        {error && (
                            <div className="text-red-400 text-center py-4 bg-red-900/20 rounded-xl border border-red-900/30 mb-4">
                                {error}
                            </div>
                        )}

                        {data && !loading && (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {/* Bull Case */}
                                <div className="bg-gray-900/50 backdrop-blur-xl border border-green-900/30 rounded-3xl p-6 shadow-xl relative overflow-hidden group">
                                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                                        <TrendingUp className="w-24 h-24 text-green-500" />
                                    </div>

                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="p-2 bg-green-500/10 rounded-xl">
                                            <TrendingUp className="w-5 h-5 text-green-400" />
                                        </div>
                                        <h3 className="text-lg font-bold text-green-100">Bull Case</h3>
                                    </div>

                                    <p className="text-gray-300 text-sm leading-relaxed">
                                        {data.bullCase}
                                    </p>
                                </div>

                                {/* Bear Case */}
                                <div className="bg-gray-900/50 backdrop-blur-xl border border-red-900/30 rounded-3xl p-6 shadow-xl relative overflow-hidden group">
                                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                                        <TrendingDown className="w-24 h-24 text-red-500" />
                                    </div>

                                    <div className="flex items-center gap-3 mb-4">
                                        <div className="p-2 bg-red-500/10 rounded-xl">
                                            <TrendingDown className="w-5 h-5 text-red-400" />
                                        </div>
                                        <h3 className="text-lg font-bold text-red-100">Bear Case</h3>
                                    </div>

                                    <p className="text-gray-300 text-sm leading-relaxed">
                                        {data.bearCase}
                                    </p>
                                </div>
                                <div className="col-span-1 md:col-span-2 text-center text-[10px] text-gray-600 mt-2">
                                    AI-generated content based on latest market data. Not financial advice.
                                </div>
                            </div>
                        )}
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
