export const KOREAN_STOCK_MAP: Record<string, { symbol: string; name: string; exchange: string }> = {
    "삼성": { symbol: "005930.KS", name: "Samsung Electronics", exchange: "KOSPI" },
    "삼성전자": { symbol: "005930.KS", name: "Samsung Electronics", exchange: "KOSPI" },
    "삼전": { symbol: "005930.KS", name: "Samsung Electronics", exchange: "KOSPI" },
    "에스케이하이닉스": { symbol: "000660.KS", name: "SK Hynix", exchange: "KOSPI" },
    "하이닉스": { symbol: "000660.KS", name: "SK Hynix", exchange: "KOSPI" },
    "sk하이닉스": { symbol: "000660.KS", name: "SK Hynix", exchange: "KOSPI" },
    "엘지에너지솔루션": { symbol: "373220.KS", name: "LG Energy Solution", exchange: "KOSPI" },
    "엘지엔솔": { symbol: "373220.KS", name: "LG Energy Solution", exchange: "KOSPI" },
    "현대차": { symbol: "005380.KS", name: "Hyundai Motor", exchange: "KOSPI" },
    "현대자동차": { symbol: "005380.KS", name: "Hyundai Motor", exchange: "KOSPI" },
    "기아": { symbol: "000270.KS", name: "Kia Corp", exchange: "KOSPI" },
    "셀트리온": { symbol: "068270.KS", name: "Celltrion", exchange: "KOSPI" },
    "포스코": { symbol: "005490.KS", name: "POSCO Holdings", exchange: "KOSPI" },
    "포스코홀딩스": { symbol: "005490.KS", name: "POSCO Holdings", exchange: "KOSPI" },
    "네이버": { symbol: "035420.KS", name: "NAVER", exchange: "KOSPI" },
    "naver": { symbol: "035420.KS", name: "NAVER", exchange: "KOSPI" },
    "카카오": { symbol: "035720.KS", name: "Kakao", exchange: "KOSPI" },
    "kakao": { symbol: "035720.KS", name: "Kakao", exchange: "KOSPI" },
    "에코프로": { symbol: "086520.KQ", name: "EcoPro", exchange: "KOSDAQ" },
    "에코프로비엠": { symbol: "247540.KQ", name: "EcoPro BM", exchange: "KOSDAQ" },
    "엘지화학": { symbol: "051910.KS", name: "LG Chem", exchange: "KOSPI" },
};
